# Generated by Django 5.0.7 on 2024-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
